### ISSUE TITLE
"Size of codebase" `max` filters not working in conjunction with "Language" filter

### ISSUE THREAD

**Issue by AML14** [seart-group/ghs#210] opened 2023-11-07 13:51 UTC
When filtering repos by "Language", e.g., `Java`, the filters related to the "Size of codebase" ("Non Blank Lines", "Code Lines" and "Comment Lines") are not working properly. While `min` filters (minimum number of lines) work as expected, `max` filters (maximum number of lines) do not.

It is worth noting that, when not using the "Language" filter, all filters related to numbers of lines work as intended (including `max` filters).

Replication:
- Query 1: `Number of Commits min = 100000` and `Language = Java` -> 65 results. ✅
- Query 2: `Number of Commits min = 100000` and `Language = Java` and `Code lines min = 1000000` -> 51 results. ✅
- Query 3: `Number of Commits min = 100000` and `Language = Java` and `Code lines max = 100` -> 65 results (should be less). ❌
- Query 4: `Number of Commits min = 1000000` -> 176 results. ✅
- Query 5: `Number of Commits min = 1000000` and `Code lines max = 100` -> 3 results. ✅

I haven't thoroughly checked if this problem affects other filters, but it seems that only line-related filters are affected.

**Comment by dabico** [comment] 2023-11-13 10:33
Debugging the generated SQL statements, I found the root cause of the issue:

```log
Hibernate: 
    select
        distinct gitrepo0_.id as id1_0_,
        gitrepo0_.branches as branches2_0_,
        gitrepo0_.commits as commits3_0_,
        gitrepo0_.contributors as contribu4_0_,
        gitrepo0_.created_at as created_5_0_,
        gitrepo0_.default_branch as default_6_0_,
        gitrepo0_.forks as forks7_0_,
        gitrepo0_.has_wiki as has_wiki8_0_,
        gitrepo0_.homepage as homepage9_0_,
        gitrepo0_.archived as archive10_0_,
        gitrepo0_.is_fork_project as is_fork11_0_,
        gitrepo0_.last_analyzed as last_an12_0_,
        gitrepo0_.last_commit as last_co13_0_,
        gitrepo0_.last_commit_sha as last_co14_0_,
        gitrepo0_.last_pinged as last_pi15_0_,
        gitrepo0_.license as license16_0_,
        gitrepo0_.language_id as languag28_0_,
        gitrepo0_.name as name17_0_,
        gitrepo0_.open_issues as open_is18_0_,
        gitrepo0_.open_pull_requests as open_pu19_0_,
        gitrepo0_.pushed_at as pushed_20_0_,
        gitrepo0_.releases as release21_0_,
        gitrepo0_.size as size22_0_,
        gitrepo0_.stargazers as stargaz23_0_,
        gitrepo0_.total_issues as total_i24_0_,
        gitrepo0_.total_pull_requests as total_p25_0_,
        gitrepo0_.updated_at as updated26_0_,
        gitrepo0_.watchers as watcher27_0_ 
    from
        git_repo gitrepo0_ 
    inner join
        language language1_ 
            on gitrepo0_.language_id=language1_.id 
    inner join
        git_repo_metrics metrics2_ 
            on gitrepo0_.id=metrics2_.repo_id 
    inner join
        language language3_ 
            on metrics2_.language_id=language3_.id 
    inner join
        git_repo_metrics metrics4_ 
            on gitrepo0_.id=metrics4_.repo_id 
    inner join
        git_repo_metrics metrics5_ 
            on gitrepo0_.id=metrics5_.repo_id 
    inner join
        git_repo_metrics metrics6_ 
            on gitrepo0_.id=metrics6_.repo_id 
    where
        language1_.name=? 
        and gitrepo0_.commits>=100000 
        and language3_.name=? 
        and metrics5_.lines_code<=100
    order by
        gitrepo0_.name asc limit ?
```

Seems like the query construction logic is wrong, and the results match repositories having _any_ language with a maximum line count of 100. This would explain why the query with the added line limitation had more results than the one without it. I'll devise a fix for this.

**Closed** 2023-11-14 12:27 UTC
Labels: bug
